import "./_group.css";
import { useMemo, useRef, useState, type ReactNode } from "react";
import { Activity, Calendar, CheckCircle, LayoutDashboard, List, Menu, Moon, SlidersHorizontal, Sun, Upload, Users, X, Search, FileText } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

type Case = { id: string; filingNumber: string; advocateId: string; partyId: string; stage: string; ageYears: number; flags: string[] };
type Summary = { total: number; ready: number; waiting: number; stages: { label: string; count: number }[]; ages: { label: string; count: number }[] };
const casesData: Case[] = [
  { id: "case-1042", filingNumber: "Crl. Appeal 1042/2019", advocateId: "ADV-018", partyId: "State / R. Kumar", stage: "Evidence", ageYears: 6, flags: ["OLD_CASE", "WAITING_WARRANT"] },
  { id: "case-0871", filingNumber: "Civil Suit 871/2020", advocateId: "ADV-042", partyId: "Mehta / Sharma", stage: "Arguments", ageYears: 5, flags: ["OLD_CASE"] },
  { id: "case-2214", filingNumber: "W.P. 2214/2023", advocateId: "ADV-007", partyId: "A. Singh / State", stage: "Admission", ageYears: 1, flags: [] },
  { id: "case-3310", filingNumber: "Crl. M.C. 3310/2024", advocateId: "ADV-031", partyId: "P. Das / State", stage: "Notice", ageYears: 0, flags: ["SERVICE_PENDING"] },
  { id: "case-1198", filingNumber: "RFA 1198/2021", advocateId: "ADV-054", partyId: "Kaur / Kaur", stage: "Evidence", ageYears: 3, flags: [] },
];
const summaryData: Summary = { total: 100, ready: 72, waiting: 28, stages: [{ label: "Admission", count: 24 }, { label: "Evidence", count: 31 }, { label: "Arguments", count: 27 }, { label: "Notice", count: 18 }], ages: [{ label: "Under 1 year", count: 18 }, { label: "1–4 years", count: 55 }, { label: "4+ years", count: 27 }] };
function useGetCases() { return { data: casesData, isLoading: false }; }
function useGetRosterSummary() { return { data: summaryData, isLoading: false }; }
function useUploadRoster() { return { isPending: false, mutate: (_args: unknown, options?: { onSuccess?: () => void }) => options?.onSuccess?.() }; }
function Link({ href, children, className }: { href: string; children: ReactNode; className?: string }) { return <a href={href} className={className} onClick={(event) => event.preventDefault()}>{children}</a>; }

const navItems = [{ path: "/", label: "Overview", icon: LayoutDashboard }, { path: "/calendar", label: "Calendar", icon: Calendar }, { path: "/roster", label: "Roster", icon: Users }, { path: "/priorities", label: "Priorities", icon: SlidersHorizontal }, { path: "/cause-list", label: "Cause List", icon: List }, { path: "/impact", label: "Impact", icon: Activity }, { path: "/finalise", label: "Finalise", icon: CheckCircle }];
function CourtShell({ children }: { children: ReactNode }) {
  const [role, setRole] = useState("Judge"); const [dark, setDark] = useState(false); const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const toggleTheme = () => { document.documentElement.classList.toggle("dark", !dark); setDark(!dark); };
  return <div className="flex min-h-[100dvh] bg-background text-foreground flex-col md:flex-row font-sans selection:bg-primary/20">
    <header className="print-hidden md:hidden flex items-center justify-between p-3 border-b border-border bg-[#162b46] text-white sticky top-0 z-40"><div className="flex items-center gap-2.5 min-w-0"><img src="/__mockup/branding/court-emblem-white.png" alt="National emblem" className="h-8 w-8 object-contain shrink-0" /><h1 className="font-serif font-semibold text-[17px] tracking-tight truncate">Cause List Configuration</h1></div><Button variant="ghost" size="icon" className="text-white hover:bg-white/10 hover:text-white" onClick={() => setMobileMenuOpen(true)}><Menu className="w-6 h-6" /></Button></header>
    <aside className={`fixed inset-y-0 left-0 z-50 w-72 md:w-64 bg-sidebar border-r border-border flex flex-col transition-transform duration-300 ease-in-out md:translate-x-0 md:static ${mobileMenuOpen ? "translate-x-0 shadow-2xl" : "-translate-x-full"}`}><div className="m-4 mb-3 p-4 rounded-2xl flex items-center justify-between bg-[#162b46] text-white shadow-lg shadow-[#162b46]/20 md:block"><div className="flex items-center gap-3"><img src="/__mockup/branding/court-emblem-white.png" alt="National emblem" className="w-10 h-10 object-contain shrink-0" /><div><h1 className="font-serif font-bold text-[16px] leading-tight tracking-tight">Cause List Configuration</h1><p className="text-[11px] text-white/65 font-medium uppercase tracking-wider">Justice Sehgal&apos;s Chamber</p></div></div><Button variant="ghost" size="icon" className="md:hidden text-white hover:bg-white/10 hover:text-white" onClick={() => setMobileMenuOpen(false)}><X className="w-5 h-5" /></Button></div>
      <nav className="flex-1 px-4 py-2 space-y-1 overflow-y-auto">{navItems.map((item) => { const isActive = item.path === "/roster"; return <Link key={item.path} href={item.path} className={`flex items-center gap-3 px-3 py-2.5 rounded-xl text-[15px] font-medium transition-all duration-200 ${isActive ? "bg-primary text-primary-foreground shadow-sm shadow-primary/20" : "text-sidebar-foreground hover:bg-black/5 dark:hover:bg-white/10 active:scale-95"}`}><item.icon className={`w-[18px] h-[18px] ${isActive ? "opacity-100" : "opacity-70"}`} />{item.label}</Link>; })}</nav>
      <div className="p-4 m-4 mt-auto rounded-2xl bg-card border shadow-sm text-sm space-y-4"><div className="text-center pb-2 border-b border-border/50"><p className="font-semibold text-[13px]">Justice Sehgal</p><p className="text-[11px] text-muted-foreground mt-0.5">Chamber Dashboard</p></div><div className="space-y-3"><div className="space-y-1.5"><label className="block text-[11px] uppercase tracking-wider text-muted-foreground font-semibold px-1" htmlFor="role-switch">Role</label><select id="role-switch" value={role} onChange={e => setRole(e.target.value)} className="w-full bg-sidebar/50 border-0 ring-1 ring-inset ring-border rounded-lg p-2 text-[14px] text-foreground"><option>Judge</option><option>Court Master</option></select></div><button type="button" onClick={toggleTheme} className="flex items-center justify-between w-full rounded-lg px-3 py-2 text-[14px] font-medium text-foreground hover:bg-black/5 dark:hover:bg-white/10" aria-label={dark ? "Switch to light mode" : "Switch to dark mode"}><span className="flex items-center gap-2 text-muted-foreground">{dark ? <Sun className="w-[18px] h-[18px]" /> : <Moon className="w-[18px] h-[18px]" />}{dark ? "Light Theme" : "Dark Theme"}</span></button></div></div>
    </aside>{mobileMenuOpen && <div className="fixed inset-0 bg-black/20 backdrop-blur-sm z-40 md:hidden" onClick={() => setMobileMenuOpen(false)} />}<main className="flex-1 flex flex-col min-w-0 bg-background md:rounded-tl-[2.5rem] md:shadow-[-8px_0_24px_-12px_rgba(0,0,0,0.1)] overflow-hidden border-l border-border relative z-0"><div className="flex-1 p-4 sm:p-6 md:p-10 max-w-5xl w-full mx-auto overflow-auto scroll-smooth">{children}</div></main>
  </div>;
}

function RosterPage() {
  const { data: summary, isLoading: sumLoading } = useGetRosterSummary(); const { data: cases, isLoading: casesLoading } = useGetCases();
  const [searchTerm, setSearchTerm] = useState(""); const [stageFilter, setStageFilter] = useState(""); const [ageFilter, setAgeFilter] = useState(""); const [advocateFilter, setAdvocateFilter] = useState(""); const [flagFilter, setFlagFilter] = useState(false); const [uploadError, setUploadError] = useState(""); const picker = useRef<HTMLInputElement>(null); const uploadRoster = useUploadRoster();
  const filteredCases = useMemo(() => { const lower = searchTerm.toLowerCase(); return (cases || []).filter(c => (c.filingNumber.toLowerCase().includes(lower) || c.id.toLowerCase().includes(lower) || c.advocateId.toLowerCase().includes(lower) || c.stage.toLowerCase().includes(lower) || c.partyId.toLowerCase().includes(lower)) && (!stageFilter || c.stage === stageFilter) && (!advocateFilter || c.advocateId.toLowerCase().includes(advocateFilter.toLowerCase())) && (!ageFilter || (ageFilter === "old" ? c.ageYears >= 4 : ageFilter === "new" ? c.ageYears < 1 : c.ageYears >= 1 && c.ageYears < 4)) && (!flagFilter || c.flags.length > 0)); }, [cases, searchTerm, stageFilter, ageFilter, advocateFilter, flagFilter]);
  if (sumLoading || casesLoading) return <div className="space-y-6"><Skeleton className="h-10 w-48" /><Skeleton className="h-[400px] w-full" /></div>;
  return <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500"><div className="flex flex-col md:flex-row md:items-center justify-between gap-4"><div><h1 className="text-3xl font-serif font-bold">Case Roster</h1><p className="text-muted-foreground mt-1">Manage and search the complete pool of cases</p></div><div className="flex items-center gap-2"><input className="sr-only" ref={picker} type="file" accept=".csv,text/csv" aria-label="Select roster CSV" onChange={e => { const file = e.target.files?.[0]; if (file && (!file.name.toLowerCase().endsWith(".csv") || file.size > 4000000)) setUploadError("Choose a CSV file smaller than 4 MB."); else { setUploadError(""); uploadRoster.mutate({ data: { csv: "" } }); } e.target.value = ""; }} /><Button onClick={() => picker.current?.click()} className="gap-2" disabled={uploadRoster.isPending}><Upload className="w-4 h-4" /> Upload Roster</Button></div></div>{uploadError && <p role="alert" className="text-sm text-destructive border border-destructive/30 rounded-md p-3">{uploadError}</p>}<p className="text-sm text-muted-foreground">Sample roster: 100 anonymised cases. Readiness is inferred from latest-hearing summaries and must be confirmed.</p>
    {summary && <><div className="grid gap-4 md:grid-cols-3">{[["Total Cases", summary.total, ""], ["No process warning found", summary.ready, "text-primary"], ["Process to Confirm", summary.waiting, "text-muted-foreground"]].map(([label, value, color]) => <Card key={label as string}><CardHeader className="pb-2"><CardTitle className="text-sm text-muted-foreground">{label}</CardTitle></CardHeader><CardContent><div className={`text-3xl font-bold font-serif ${color}`}>{value}</div></CardContent></Card>)}</div><div className="grid md:grid-cols-2 gap-4"><Card className="p-5"><h2 className="font-semibold mb-3">Cases by stage</h2>{summary.stages.map(s => <div key={s.label} className="mb-2 text-sm"><div className="flex justify-between"><span>{s.label}</span><span>{s.count}</span></div><div className="h-2 bg-muted rounded-full"><div className="h-full bg-primary rounded-full" style={{ width: `${s.count / summary.total * 100}%` }} /></div></div>)}</Card><Card className="p-5"><h2 className="font-semibold mb-3">Cases by age</h2>{summary.ages.map(s => <div key={s.label} className="mb-2 text-sm"><div className="flex justify-between"><span>{s.label}</span><span>{s.count}</span></div><div className="h-2 bg-muted rounded-full"><div className="h-full bg-primary rounded-full" style={{ width: `${s.count / summary.total * 100}%` }} /></div></div>)}</Card></div></>}
    <Card><CardHeader className="border-b"><div className="flex items-center gap-4"><div className="relative flex-1 max-w-md"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" /><Input placeholder="Search by filing number, party, or stage..." className="pl-9" value={searchTerm} onChange={e => setSearchTerm(e.target.value)} /></div><select aria-label="Filter by stage" className="border rounded-md p-2 bg-background" value={stageFilter} onChange={e => setStageFilter(e.target.value)}><option value="">All stages</option>{[...new Set(cases?.map(c => c.stage) || [])].sort().map(s => <option key={s}>{s}</option>)}</select><select aria-label="Filter by age" className="border rounded-md p-2 bg-background" value={ageFilter} onChange={e => setAgeFilter(e.target.value)}><option value="">All ages</option><option value="new">Under 1 year</option><option value="mid">1–4 years</option><option value="old">4+ years</option></select><Input aria-label="Filter by advocate" placeholder="Advocate ID" className="max-w-32" value={advocateFilter} onChange={e => setAdvocateFilter(e.target.value)} /><label className="flex items-center gap-2 text-sm whitespace-nowrap"><input type="checkbox" checked={flagFilter} onChange={e => setFlagFilter(e.target.checked)} /> Flagged only</label></div></CardHeader><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Filing No.</TableHead><TableHead>Stage</TableHead><TableHead>Age (Years)</TableHead><TableHead>Advocate</TableHead><TableHead>Flags</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody>{filteredCases.map(c => <TableRow key={c.id}><TableCell className="font-medium"><Link href={`/roster/${c.id}`} className="hover:underline flex items-center gap-2"><FileText className="w-4 h-4 text-primary" />{c.filingNumber}</Link></TableCell><TableCell>{c.stage}</TableCell><TableCell><span className={c.ageYears > 5 ? "text-destructive font-semibold" : ""}>{c.ageYears}</span></TableCell><TableCell>{c.advocateId}</TableCell><TableCell><div className="flex gap-1 flex-wrap">{c.flags.map(f => <Badge key={f} variant="outline" className="text-[10px]">{f}</Badge>)}</div></TableCell><TableCell className="text-right"><Button variant="ghost" size="sm" asChild><Link href={`/roster/${c.id}`}>View</Link></Button></TableCell></TableRow>)}{filteredCases.length === 0 && <TableRow><TableCell colSpan={6} className="text-center py-8 text-muted-foreground">No cases found.</TableCell></TableRow>}</TableBody></Table></div></Card>
  </div>;
}
export function Current() { return <CourtShell><RosterPage /></CourtShell>; }