// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/court-overview-ios/IOS.tsx": () => import("../components/mockups/court-overview-ios/IOS.tsx"),
  "./components/mockups/court-overview/Current.tsx": () => import("../components/mockups/court-overview/Current.tsx"),
  "./components/mockups/court-overview/Refined.tsx": () => import("../components/mockups/court-overview/Refined.tsx"),
  "./components/mockups/court-roster-refined/Refined.tsx": () => import("../components/mockups/court-roster-refined/Refined.tsx"),
  "./components/mockups/court-roster/Current.tsx": () => import("../components/mockups/court-roster/Current.tsx")
};
