// Named genomes: every redesign, every baseline and every judge style as a point in the zoo's space, so the
// tournament can start from them and report against them. Values are each source's own defaults (the
// redesigns' tuned settings, the baselines' and judges' current code); where a source's idea is
// approximated rather than copied, the comment says how.

import type { Genome } from "./genome";

/** The original benchtime (knapsack, desk, check-in, earliest next date with room), the common ancestor. */
const BASE: Genome = {
  selection: "knapsack",
  firstDates: "priority",
  nextDate: "earliest",
  coverage: "none",
  callOrder: "short",
  calibration: "off",
  caseEstimate: true,
  priorCheck: false,
  desk: true,
  checkin: true,
  checkinRobust: false,
  cluster: true,
  callTimes: true,
  fillTarget: 0.95,
  standbyShare: 0.1,
  promiseFill: 0.95,
  initialFill: 1,
  firstOldShare: 0.15,
  weights: { throughput: 1, disposal: 0, fairness: 1, trips: 1, predictability: 1 },
  ageExponent: 1,
  ageingFloor: 0.15,
  enforceFloor: true,
  windowDays: 20,
  relistDays: 7,
  relistCap: 0.8,
  quickRelist: true,
  gapOfHeard: false,
  countDiary: false,
  countCap: 60,
  pendingHold: 0,
  returnMargin: 1,
  recheckDays: 7,
  rotationDays: 40,
  rotationCap: 0.5,
  rotationAll: false,
  reviewDays: 0,
  mentionAfter: 1,
  portfolioOld: 0.35,
  blocks: "none",
  purposeDays: false,
  carryForward: false,
};

const g = (over: Partial<Genome>): Genome => ({ ...BASE, ...over, weights: { ...BASE.weights, ...(over.weights ?? {}) } });

/** The baselines as the zoo expresses them: PUCAR's prior only, no desk, no check-in, no floor, no call times. */
const BASELINE: Partial<Genome> = {
  caseEstimate: false,
  priorCheck: false,
  calibration: "off",
  desk: false,
  checkin: false,
  checkinRobust: false,
  cluster: false,
  callTimes: false,
  callOrder: "rank",
  fillTarget: 1,
  standbyShare: 0,
  promiseFill: 1,
  enforceFloor: false,
  quickRelist: false,
  gapOfHeard: false,
  firstDates: "spread",
  nextDate: "pucar",
};

export const PRESETS: Record<string, Genome> = {
  // ---- baselines (src/planner/baselines.ts)
  status_quo_60: g({ ...BASELINE, selection: "listAll", nextDate: "flat60", countDiary: true, countCap: 60 }),
  status_quo_ref: g({ ...BASELINE, selection: "listAll", nextDate: "pucar", countDiary: true, countCap: 90 }),
  fifo_capped: g({ ...BASELINE, selection: "fifo" }),
  bin_packing: g({ ...BASELINE, selection: "ppm" }),
  oldest_first: g({ ...BASELINE, selection: "oldest", firstDates: "priority", initialFill: 1 }),
  // ---- the case study's judges (src/planner/judges.ts)
  sehgal: g({ ...BASELINE, selection: "fifo", blocks: "sehgal", fillTarget: 1.3, promiseFill: 1.3, carryForward: true, callTimes: true }),
  dimakar: g({ ...BASELINE, selection: "oldest", purposeDays: true, callOrder: "cluster", firstDates: "priority", initialFill: 1, quickRelist: true, weights: { throughput: 1, disposal: 0, fairness: 2, trips: 1, predictability: 1 } }),
  joshi: g({ ...BASELINE, selection: "youngest", enforceFloor: true, coverage: "none", firstDates: "priority", initialFill: 1, firstOldShare: 0.15, weights: { throughput: 1, disposal: 0, fairness: 0, trips: 1, predictability: 1 } }),
  // ---- the seven redesigns (/tmp/variants/*, scored on the old world)
  // G: one index per case, filled in index order; failure-rate calibration; review calls; relist cap 1.2
  // (its learned check-in cut is approximated by the robust check-in)
  g_index: g({
    selection: "index",
    callOrder: "rank",
    firstDates: "priority",
    initialFill: 0.65,
    nextDate: "earliest",
    gapOfHeard: true,
    relistCap: 1.2,
    fillTarget: 1.05,
    standbyShare: 0.05,
    promiseFill: 1.05,
    checkinRobust: true,
    reviewDays: 7,
    calibration: "fail",
    priorCheck: true,
    weights: { throughput: 1, disposal: 2, fairness: 1, trips: 1, predictability: 1 },
    ageExponent: 1.5,
  }),
  // C: daily budgets (old never-heard 35%, disposal 15%, early 30%), old-first first dates, promise fill 1.3,
  // failure calibration, release-once check-in, the 2-minute order call after a desk visit
  c_portfolio: g({
    selection: "portfolio",
    portfolioOld: 0.35,
    firstDates: "priority",
    firstOldShare: 0.7,
    initialFill: 0.85,
    promiseFill: 1.3,
    fillTarget: 0.95,
    standbyShare: 0.15,
    checkinRobust: true,
    coverage: "mention",
    mentionAfter: 1,
    calibration: "fail",
    priorCheck: true,
    pendingHold: 0.3,
  }),
  // B: joint first dates with projected returns, 4y+ first 45%, gap of the purpose heard, return margin 1.3,
  // desk re-check 21 days, 2-minute coverage mentions
  b_horizon: g({
    firstDates: "horizon",
    firstOldShare: 0.45,
    fillTarget: 1.1,
    promiseFill: 1.1,
    returnMargin: 1.3,
    recheckDays: 21,
    coverage: "mention",
    mentionAfter: 0,
    gapOfHeard: true,
    pendingHold: 0.5,
    priorCheck: true,
  }),
  // D: today's list minus knowable waste; old and judgment first, then 10-point likelihood bands; cap 110%;
  // next dates within 20 working days of the gap; per-type rate learned from the docket
  d_simple: g({
    selection: "simple",
    callOrder: "simple",
    firstDates: "spread",
    fillTarget: 1.1,
    standbyShare: 0,
    promiseFill: 1.1,
    calibration: "learned",
    nextDate: "window",
    windowDays: 20,
    gapOfHeard: true,
    relistDays: 14,
    cluster: false,
  }),
  // A: knapsack with disposals weighted, a 40-working-day rotation for 4+ year cases with review calls for
  // blocked ones, old cases spread over the first rotation, success-rate calibration
  a_fillfair: g({
    coverage: "rotation",
    rotationDays: 40,
    rotationCap: 0.5,
    reviewDays: 60,
    firstDates: "rotation",
    initialFill: 0.5,
    promiseFill: 1,
    fillTarget: 1.05,
    standbyShare: 0.05,
    calibration: "pscale",
    priorCheck: true,
    pendingHold: 1,
    weights: { throughput: 1, disposal: 1.5, fairness: 1, trips: 1, predictability: 1 },
  }),
  // F: the myopic knapsack (look-ahead did not beat it) with its calibration
  f_lookahead: g({ calibration: "pscale", priorCheck: true }),
  // E: the dial search's chosen point (stage multipliers not expressible; the rest as found)
  e_search: g({
    fillTarget: 0.86,
    promiseFill: 0.8,
    standbyShare: 0.16,
    coverage: "rotation",
    rotationDays: 39,
    ageingFloor: 0.41,
    weights: { throughput: 1, disposal: 0.28, fairness: 3, trips: 0.09, predictability: 1 },
    nextDate: "pucar",
    relistDays: 14,
    cluster: false,
    desk: false,
    checkin: true,
  }),
  // the original benchtime (before the redesigns)
  benchtime_v0: g({}),
};

/** Presets that are candidates for benchtime (they honour the 15% floor); the rest are comparators only. */
export const CANDIDATE_PRESETS = Object.keys(PRESETS).filter((k) => PRESETS[k]!.enforceFloor);

/** The tournament's pick under the final rule (g237, out/tournament/winner.json, written 14:56 IST): Daily list: one priority index per case (value of a hearing today plus the waiting cost it stops, less wasted trips, per minute), filled to 111% of the day with a 30% standby list. Next dates: the earliest day with room after PUCAR's gap (failed or unheard matters sooner). Process desk: matters whose summons, notice or warrant is not back are handled at the desk. No check-in. Every 4+ year case before the bench at least every 45 working days. */
export const TOURNAMENT_WINNER: Genome = {
  "selection": "index",
  "firstDates": "spread",
  "nextDate": "earliest",
  "coverage": "rotation",
  "callOrder": "cluster",
  "calibration": "off",
  "caseEstimate": true,
  "priorCheck": true,
  "desk": true,
  "checkin": false,
  "checkinRobust": false,
  "cluster": true,
  "callTimes": false,
  "fillTarget": 1.105,
  "standbyShare": 0.3,
  "promiseFill": 1.204,
  "initialFill": 0.95,
  "firstOldShare": 0.209,
  "weights": {
    "throughput": 1.643,
    "disposal": 1.622,
    "fairness": 2.619,
    "trips": 1.883,
    "predictability": 3
  },
  "ageExponent": 0.802,
  "ageingFloor": 0.33,
  "enforceFloor": true,
  "windowDays": 5,
  "relistDays": 11,
  "relistCap": 1.045,
  "quickRelist": true,
  "gapOfHeard": true,
  "countDiary": false,
  "countCap": 85,
  "pendingHold": 0.44,
  "returnMargin": 1.376,
  "recheckDays": 12,
  "rotationDays": 45,
  "rotationCap": 0.34,
  "reviewDays": 11,
  "mentionAfter": 0,
  "portfolioOld": 0.191,
  "blocks": "none",
  "purposeDays": false,
  "carryForward": false,
  "rotationAll": false
};
PRESETS.tournament_winner = TOURNAMENT_WINNER;

/** The zoo's default: the tournament's pick. */
export const DEFAULT_GENOME: Genome = TOURNAMENT_WINNER;

// Aims a judge can choose (the "what should the list aim for?" setting). Each is the best genome the final
// tournament stage found for one aim, among genomes that honour at least 85 per cent of dates and leave at most
// 5 old cases unheard (seeds 1-6, fresh runs on the shared court); "balanced" is the tournament winner. The cost
// of each is measured, not assumed: see out/aims.json and the held-out experiments.
export const AIM_GENOMES: Record<string, Genome> = {
 "balanced": {
  "selection": "index",
  "firstDates": "spread",
  "nextDate": "earliest",
  "coverage": "rotation",
  "callOrder": "cluster",
  "calibration": "off",
  "caseEstimate": true,
  "priorCheck": true,
  "desk": true,
  "checkin": false,
  "checkinRobust": false,
  "cluster": true,
  "callTimes": false,
  "fillTarget": 1.105,
  "standbyShare": 0.3,
  "promiseFill": 1.204,
  "initialFill": 0.95,
  "firstOldShare": 0.209,
  "weights": {
   "throughput": 1.643,
   "disposal": 1.622,
   "fairness": 2.619,
   "trips": 1.883,
   "predictability": 3
  },
  "ageExponent": 0.802,
  "ageingFloor": 0.33,
  "enforceFloor": true,
  "windowDays": 5,
  "relistDays": 11,
  "relistCap": 1.045,
  "quickRelist": true,
  "gapOfHeard": true,
  "countDiary": false,
  "countCap": 85,
  "pendingHold": 0.44,
  "returnMargin": 1.376,
  "recheckDays": 12,
  "rotationDays": 45,
  "rotationCap": 0.34,
  "reviewDays": 11,
  "mentionAfter": 0,
  "portfolioOld": 0.191,
  "blocks": "none",
  "purposeDays": false,
  "carryForward": false,
  "rotationAll": false
 },
 "focus_hearings": {
  "selection": "ppm",
  "firstDates": "horizon",
  "nextDate": "window",
  "coverage": "mention",
  "callOrder": "rank",
  "calibration": "pscale",
  "caseEstimate": true,
  "priorCheck": true,
  "desk": true,
  "checkin": true,
  "checkinRobust": false,
  "cluster": true,
  "callTimes": true,
  "fillTarget": 1.1,
  "standbyShare": 0.149,
  "promiseFill": 1.164,
  "initialFill": 1,
  "firstOldShare": 0.667,
  "weights": {
   "throughput": 0.711,
   "disposal": 2.887,
   "fairness": 1,
   "trips": 0.196,
   "predictability": 1.691
  },
  "ageExponent": 1,
  "ageingFloor": 0.15,
  "enforceFloor": true,
  "windowDays": 35,
  "relistDays": 13,
  "relistCap": 0.934,
  "quickRelist": true,
  "gapOfHeard": true,
  "countDiary": false,
  "countCap": 60,
  "pendingHold": 0.5,
  "returnMargin": 1.05,
  "recheckDays": 21,
  "rotationDays": 40,
  "rotationCap": 0.5,
  "reviewDays": 0,
  "mentionAfter": 0,
  "portfolioOld": 0.35,
  "blocks": "none",
  "purposeDays": false,
  "carryForward": false,
  "rotationAll": false
 },
 "focus_finish": {
  "selection": "simple",
  "firstDates": "horizon",
  "nextDate": "earliest",
  "coverage": "floor",
  "callOrder": "rank",
  "calibration": "learned",
  "caseEstimate": true,
  "priorCheck": true,
  "desk": false,
  "checkin": false,
  "checkinRobust": false,
  "cluster": true,
  "callTimes": false,
  "fillTarget": 1.105,
  "standbyShare": 0.279,
  "promiseFill": 1.183,
  "initialFill": 0.918,
  "firstOldShare": 0.15,
  "weights": {
   "throughput": 1.643,
   "disposal": 1.335,
   "fairness": 1.832,
   "trips": 1.856,
   "predictability": 2.59
  },
  "ageExponent": 1.774,
  "ageingFloor": 0.412,
  "enforceFloor": true,
  "windowDays": 12,
  "relistDays": 11,
  "relistCap": 0.936,
  "quickRelist": true,
  "gapOfHeard": true,
  "countDiary": false,
  "countCap": 100,
  "pendingHold": 0.743,
  "returnMargin": 1.39,
  "recheckDays": 11,
  "rotationDays": 31,
  "rotationCap": 0.34,
  "reviewDays": 8,
  "mentionAfter": 0,
  "portfolioOld": 0.292,
  "blocks": "none",
  "purposeDays": false,
  "carryForward": false,
  "rotationAll": false
 },
 "keep_dates": {
  "selection": "index",
  "firstDates": "spread",
  "nextDate": "earliest",
  "coverage": "floor",
  "callOrder": "rank",
  "calibration": "off",
  "caseEstimate": true,
  "priorCheck": true,
  "desk": true,
  "checkin": false,
  "checkinRobust": true,
  "cluster": false,
  "callTimes": false,
  "fillTarget": 1.105,
  "standbyShare": 0.279,
  "promiseFill": 1.122,
  "initialFill": 0.978,
  "firstOldShare": 0.196,
  "weights": {
   "throughput": 1.188,
   "disposal": 1.335,
   "fairness": 2.208,
   "trips": 0.687,
   "predictability": 2.674
  },
  "ageExponent": 0.532,
  "ageingFloor": 0.386,
  "enforceFloor": true,
  "windowDays": 12,
  "relistDays": 11,
  "relistCap": 1.045,
  "quickRelist": true,
  "gapOfHeard": false,
  "countDiary": false,
  "countCap": 85,
  "pendingHold": 0.474,
  "returnMargin": 1.308,
  "recheckDays": 10,
  "rotationDays": 31,
  "rotationCap": 0.356,
  "reviewDays": 0,
  "mentionAfter": 1,
  "portfolioOld": 0.308,
  "blocks": "none",
  "purposeDays": false,
  "carryForward": false,
  "rotationAll": true
 },
 "reach_everyone": {
  "selection": "index",
  "firstDates": "spread",
  "nextDate": "flat60",
  "coverage": "floor",
  "callOrder": "rank",
  "calibration": "pscale",
  "caseEstimate": true,
  "priorCheck": true,
  "desk": false,
  "checkin": false,
  "checkinRobust": true,
  "cluster": true,
  "callTimes": false,
  "fillTarget": 1.5,
  "standbyShare": 0.178,
  "promiseFill": 1.204,
  "initialFill": 0.918,
  "firstOldShare": 0.196,
  "weights": {
   "throughput": 1.643,
   "disposal": 1.622,
   "fairness": 2.743,
   "trips": 1.629,
   "predictability": 1.927
  },
  "ageExponent": 0.532,
  "ageingFloor": 0.176,
  "enforceFloor": true,
  "windowDays": 13,
  "relistDays": 12,
  "relistCap": 1.045,
  "quickRelist": true,
  "gapOfHeard": true,
  "countDiary": false,
  "countCap": 87,
  "pendingHold": 0.743,
  "returnMargin": 1.39,
  "recheckDays": 12,
  "rotationDays": 31,
  "rotationCap": 0.315,
  "reviewDays": 0,
  "mentionAfter": 0,
  "portfolioOld": 0.292,
  "blocks": "none",
  "purposeDays": false,
  "carryForward": false,
  "rotationAll": false
 },
 "least_waiting": {
  "selection": "oldest",
  "firstDates": "spread",
  "nextDate": "earliest",
  "coverage": "floor",
  "callOrder": "simple",
  "calibration": "learned",
  "caseEstimate": true,
  "priorCheck": false,
  "desk": false,
  "checkin": false,
  "checkinRobust": true,
  "cluster": false,
  "callTimes": true,
  "fillTarget": 1.5,
  "standbyShare": 0.186,
  "promiseFill": 1.126,
  "initialFill": 0.981,
  "firstOldShare": 0.178,
  "weights": {
   "throughput": 1.856,
   "disposal": 0.748,
   "fairness": 2.683,
   "trips": 0.611,
   "predictability": 2.063
  },
  "ageExponent": 1.092,
  "ageingFloor": 0.318,
  "enforceFloor": true,
  "windowDays": 23,
  "relistDays": 13,
  "relistCap": 1.269,
  "quickRelist": true,
  "gapOfHeard": true,
  "countDiary": false,
  "countCap": 68,
  "pendingHold": 0.902,
  "returnMargin": 1.26,
  "recheckDays": 14,
  "rotationDays": 12,
  "rotationCap": 0.257,
  "reviewDays": 0,
  "mentionAfter": 0,
  "portfolioOld": 0.352,
  "blocks": "none",
  "purposeDays": false,
  "carryForward": false,
  "rotationAll": false
 }
};
